# fly.toml app configuration file generated for scrapydoo on 2023-08-29T12:58:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scrapydoo"
primary_region = "sin"

[build]
  dockerfile = "./docker/prod/Dockerfile"

[env]
  SCRAPYD_URL = "https://scrapydoo.zube.dev"

[[mounts]]
  source = "scrapyd_data"
  destination = "/var/lib/scrapyd"

[http_service]
  internal_port = 6800
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.scrapyd]
    port = 6800
    type = "tcp"
    grace_period = "10s"
    interval = "10s"
