#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# set scrapyd username and password
sed -i "s/username.*/username = ${SCRAPYD_USERNAME}/" scrapyd.conf
sed -i "s/password.*/password = ${SCRAPYD_PASSWORD}/" scrapyd.conf

chown -R scrapydoo:scrapydoo /var/lib/scrapyd

exec gosu scrapydoo "$@"
