#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

docker run --rm --detach --name scrapyd \
    --publish 6800:6800 \
    --env-file scrapydoo.env \
    --network scrapydoo-net \
    --label caddy=scrapydoo.zube.dev \
    --label caddy.reverse_proxy="{{upstreams 6800}}" \
    ziibii88/scrapydoo:latest /start
